services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        networks:
            - kesai-transcoder

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        networks:
            - kesai-transcoder
        volumes:
            - ./data/outputs:/outputs
            - ./data/sqlite:/sqlite
            - ./data/uploads:/uploads

    reverse-proxy:
        image: nginx:stable-alpine
        container_name: reverse-proxy
        depends_on:
            - frontend
            - backend
        ports:
            - '4000:80'
        volumes:
            - ./nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - kesai-transcoder

networks:
    kesai-transcoder:
        driver: bridge
